image: node:latest
variable:
  script:
    - echo $YUQUE_TOKEN
pages:
  script:
    - npm install
    - npm run gitlab-yuque
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
      - yuque
    key: project
  only:
    - master
